"""empty message

Revision ID: 11eb397428a2
Revises: 
Create Date: 2023-04-06 13:47:29.896380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11eb397428a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('image_url1', sa.String(length=400), nullable=True),
    sa.Column('image_url2', sa.String(length=400), nullable=True),
    sa.Column('image_url3', sa.String(length=400), nullable=True),
    sa.Column('image_url4', sa.String(length=400), nullable=True),
    sa.Column('quote', sa.String(length=80), nullable=True),
    sa.Column('quoted', sa.String(length=80), nullable=True),
    sa.Column('offerer', sa.String(length=80), nullable=True),
    sa.Column('dimensions', sa.String(length=80), nullable=True),
    sa.Column('materials', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=True),
    sa.Column('country_of_origin', sa.String(length=40), nullable=True),
    sa.Column('user_email', sa.String(length=40), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('amount_of_bid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('letter', sa.String(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    op.drop_table('piece')
    # ### end Alembic commands ###
